### ISSUE TITLE
Duda

### ISSUE THREAD

**Issue by PatriciaManriques** [PatriciaManriques/ProgramacionIII#2]
@jruitti  Javi, cuando tengo que hacer el paso del Mapeo no me lo genera, llega hasta el punto donde le doy Ok. Y no pasa mas nada, de igual modo ya lo subí al repositorio al avance que hice

**Comment by jruitti** [comment]
Pasame capturas de pantalla para ver que tipo de error te esta dando, y en que paso sucede
